// DEMO_STEPS and DEMO_BASE are set in demo_config.js (generated by generate_demo_data.py)

const mainImg = document.getElementById('main-image');
const latticeImg = document.getElementById('lattice-image');
const energyImg = document.getElementById('energy-image');
const seamImg = document.getElementById('seam-image');
const slider = document.getElementById('step-slider');
const stepLabel = document.getElementById('step-label');

function stepDir(step) {
  return `${DEMO_BASE}/step_${String(step).padStart(3, '0')}`;
}

const IMAGE_TYPES = ['image', 'lattice_space', 'energy', 'seam_overlay'];

// Preloaded Image objects for instant switching
let imageCache = {};

function preloadStep(step) {
  if (imageCache[step]) return;
  imageCache[step] = {};
  const dir = stepDir(step);
  for (const type of IMAGE_TYPES) {
    const img = new Image();
    img.src = `${dir}/${type}.png`;
    imageCache[step][type] = img;
  }
}

function showStep(step) {
  // Use cached images if available, fall back to direct src
  const cached = imageCache[step];
  if (cached) {
    mainImg.src = cached['image'].src;
    latticeImg.src = cached['lattice_space'].src;
    energyImg.src = cached['energy'].src;
    seamImg.src = cached['seam_overlay'].src;
  } else {
    const dir = stepDir(step);
    mainImg.src = `${dir}/image.png`;
    latticeImg.src = `${dir}/lattice_space.png`;
    energyImg.src = `${dir}/energy.png`;
    seamImg.src = `${dir}/seam_overlay.png`;
  }
  stepLabel.textContent = `Step: ${step} / ${DEMO_STEPS}`;
}

slider.addEventListener('input', () => {
  showStep(parseInt(slider.value, 10));
});

// Keyboard navigation
document.addEventListener('keydown', (e) => {
  const current = parseInt(slider.value, 10);
  if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') {
    const next = Math.max(0, current - 1);
    slider.value = next;
    showStep(next);
  } else if (e.key === 'ArrowRight' || e.key === 'ArrowUp') {
    const next = Math.min(DEMO_STEPS, current + 1);
    slider.value = next;
    showStep(next);
  }
});

// Initialize
if (typeof DEMO_STEPS === 'undefined') {
  stepLabel.textContent = 'Error: run generate_demo_data.py first';
} else {
  slider.max = DEMO_STEPS;
  slider.value = 0;

  // Preload all steps
  for (let i = 0; i <= DEMO_STEPS; i++) {
    preloadStep(i);
  }

  showStep(0);
}
