// DEMOS and DEMO_DATA_ROOT are set in demo_config.js (generated by generate_demo_data.py)

const mainImg = document.getElementById('main-image');
const latticeImg = document.getElementById('lattice-image');
const energyImg = document.getElementById('energy-image');
const seamImg = document.getElementById('seam-image');
const slider = document.getElementById('step-slider');
const stepLabel = document.getElementById('step-label');
const showSeamsCheckbox = document.getElementById('show-seams');
const showLatticeCheckbox = document.getElementById('show-lattice');
const demoSelect = document.getElementById('demo-select');

const IMAGE_TYPES = ['image', 'image_seams', 'image_lattice', 'lattice_space', 'energy', 'seam_overlay'];

let currentDemo = null;
let maxStep = 0;
let imageCache = {};

function stepDir(demoName, step) {
  return `${DEMO_DATA_ROOT}/${demoName}/step_${String(step).padStart(3, '0')}`;
}

function preloadStep(demoName, step) {
  const key = `${demoName}/${step}`;
  if (imageCache[key]) return;
  imageCache[key] = {};
  const dir = stepDir(demoName, step);
  for (const type of IMAGE_TYPES) {
    const img = new Image();
    img.src = `${dir}/${type}.png`;
    imageCache[key][type] = img;
  }
}

function getMainType() {
  if (showLatticeCheckbox.checked) return 'image_lattice';
  if (showSeamsCheckbox.checked) return 'image_seams';
  return 'image';
}

function showStep(step) {
  if (!currentDemo) return;
  const mainType = getMainType();
  const key = `${currentDemo.name}/${step}`;
  const cached = imageCache[key];
  if (cached) {
    mainImg.src = cached[mainType].src;
    latticeImg.src = cached['lattice_space'].src;
    energyImg.src = cached['energy'].src;
    seamImg.src = cached['seam_overlay'].src;
  } else {
    const dir = stepDir(currentDemo.name, step);
    mainImg.src = `${dir}/${mainType}.png`;
    latticeImg.src = `${dir}/lattice_space.png`;
    energyImg.src = `${dir}/energy.png`;
    seamImg.src = `${dir}/seam_overlay.png`;
  }
  stepLabel.textContent = `Step: ${step} / ${maxStep}`;
}

function loadDemo(demo) {
  currentDemo = demo;
  maxStep = demo.steps;
  slider.max = maxStep;
  slider.value = 0;

  for (let i = 0; i <= maxStep; i++) {
    preloadStep(demo.name, i);
  }

  showStep(0);
}

// Demo selector
demoSelect.addEventListener('change', () => {
  const demo = DEMOS[demoSelect.selectedIndex];
  loadDemo(demo);
});

slider.addEventListener('input', () => {
  showStep(parseInt(slider.value, 10));
});

showSeamsCheckbox.addEventListener('change', () => {
  // Mutually exclusive with lattice overlay
  if (showSeamsCheckbox.checked) showLatticeCheckbox.checked = false;
  showStep(parseInt(slider.value, 10));
});

showLatticeCheckbox.addEventListener('change', () => {
  if (showLatticeCheckbox.checked) showSeamsCheckbox.checked = false;
  showStep(parseInt(slider.value, 10));
});

// Keyboard navigation
document.addEventListener('keydown', (e) => {
  if (document.activeElement === demoSelect) return;

  const current = parseInt(slider.value, 10);
  if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') {
    const next = Math.max(0, current - 1);
    slider.value = next;
    showStep(next);
  } else if (e.key === 'ArrowRight' || e.key === 'ArrowUp') {
    const next = Math.min(maxStep, current + 1);
    slider.value = next;
    showStep(next);
  } else if (e.key === 's' || e.key === 'S') {
    showSeamsCheckbox.checked = !showSeamsCheckbox.checked;
    if (showSeamsCheckbox.checked) showLatticeCheckbox.checked = false;
    showStep(current);
  } else if (e.key === 'l' || e.key === 'L') {
    showLatticeCheckbox.checked = !showLatticeCheckbox.checked;
    if (showLatticeCheckbox.checked) showSeamsCheckbox.checked = false;
    showStep(current);
  }
});

// Initialize
if (typeof DEMOS === 'undefined' || DEMOS.length === 0) {
  stepLabel.textContent = 'Error: run generate_demo_data.py first';
} else {
  for (const demo of DEMOS) {
    const opt = document.createElement('option');
    opt.textContent = demo.title;
    demoSelect.appendChild(opt);
  }

  loadDemo(DEMOS[0]);
}
