// Auto-generated by generate_demo_data.py — do not edit
const DEMOS = [
  { name: "synthetic_bagel_shrink", title: "Synthetic Bagel -- Shrink", steps: 20 },
  { name: "synthetic_bagel_grow", title: "Synthetic Bagel -- Grow", steps: 20 },
  { name: "arch_shrink", title: "Arch -- Shrink", steps: 15 },
  { name: "arch_grow", title: "Arch -- Grow", steps: 15 },
  { name: "river_shrink", title: "River -- Shrink", steps: 15 },
  { name: "river_grow", title: "River -- Grow", steps: 15 },
];
const DEMO_DATA_ROOT = "../demo_data";
