// Auto-generated by generate_demo_data.py — do not edit
const DEMOS = [
  { name: "synthetic_bagel", title: "Synthetic Bagel — Shrink Ring Body", steps: 18 },
  { name: "arch", title: "Arch — Thin the Arch Body", steps: 15 },
  { name: "river", title: "River — Narrow the Stream", steps: 15 },
];
const DEMO_DATA_ROOT = "../demo_data";
